---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-openshift-plus
placementBindingDefaults:
  name: policy-openshift-plus
policyDefaults:
  placement:
    placementName: placement-odf
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  consolidateManifests: false
  disabled: false
  namespace: open-cluster-management-global-set
  pruneObjectBehavior: "DeleteAll"
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53
  policyAnnotations: {"argocd.argoproj.io/compare-options": "IgnoreExtraneous"}
policies:
  - name: odf
    manifests:
      - path: input-odf/
        kustomizeOptions:
          enableAlphaPlugins: true
          enableHelm: true
# - name: policy-odf
#   categories:
#     - SI System and Information Integrity
#   controls: 
#     - SI-7 Software Firmware and Information Integrity
#   manifests:
#     - path: input-odf/policy-odf.yaml
# - name: policy-odf-status
#   categories:
#     - SI System and Information Integrity
#   controls: 
#     - SI-7 Software Firmware and Information Integrity
#   dependencies:
#     - name: policy-odf
#   manifests:
#     - path: input-odf/policy-odf-status.yaml
#   remediationAction: inform
