---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: odf
  namespace: open-cluster-management-global-set
  labels:
    rht-gitops.com/open-cluster-management-global-set: policies
spec:
  goTemplate: true
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: placement-all-openshift
      requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: odf-{{.name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: "{{.server}}"
        namespace: open-cluster-management-global-set
      source:
        repoURL: https://github.com/eformat/odf-policy.git
        path: policy-sets/stable/openshift-plus
        targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
