apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-openshift-plus-clusters
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: vendor, operator: In, values: ["OpenShift"]}
          - {key: name, operator: NotIn, values: ["local-cluster"]}
          - {key: odf, operator: In, values: ["true"]}
